### ISSUE TITLE
Personal Deliverables

### ISSUE THREAD

**Issue by jrm947** [sagedemage/steam_game_review#28]
# Personal Deliverables
## Required Steam API
- GetAppList: 
  - [GET- GetAppList](https://steamapi.xpaw.me/#IStoreService/GetAppList)
- GetOwnedGames
  - [GET - GetOwnedGames](https://steamapi.xpaw.me/#IPlayerService/GetOwnedGames)
  
## Tasks 
- [x] 1. Ability to recommend games to people
- [x] 2. Ability for people to rate games in their library
- [x] 3. Ability to search through and view games and their library
- [x] 4. Review on games
- [x] 5. Ability to see other players' reviews
- [ ] 6. Watchlist for upcoming games (Calendar, or Push Notifications)
  - Might not be possible to finish

## Get Image
```
https://steamcdn-a.akamaihd.net/steam/apps/{appId}/header.jpg
```
  
## Resources
- [Axios](https://axios-http.com/docs/intro)
- [GET Request](https://axios-http.com/docs/example)
