### ISSUE TITLE
Character Length for passHash is too small

### ISSUE THREAD

**Issue by sagedemage** [sagedemage/steam_game_review#9]
The character length for the passHash should be 255. 

The passHash attribute for creating a table should look like this.
```
passHash varchar(255) not null,
```

## Tasks
- [x] change passHash data type to varchar(255)
- [x] change username data type to varchar(30)
- [x] change email data type to varchar(255)
